title: Baburam Chaudhary
logo: /assets/img/profile_pic.jpg
description: |
  AI/ML Researcher<br>
  ğŸ“ Address: Ghorahi-03, Dang<br>
  âœ‰ï¸ Email: baburam.ch208@gmail.com<br>
  ğŸ“ Phone: +977-9840425918<br>
  ğŸ’» Github: <a href="https://github.com/Baburam208" target="_blank">https://github.com/Baburam208</a>  <br>
  ğŸ”— LinkedIn: <a href="https://www.linkedin.com/in/baburamchaudhary/" target="_blank">https://www.linkedin.com/in/baburamchaudhary/</a>  <br>
# show_downloads: true
theme: jekyll-theme-minimal
